### PR TITLE
updating nhd_centroids.csv file

### PR DESCRIPTION
**Pull request by mhines-usgs**
@lawinslow

### CODE REVIEW

**Comment by lawinslow** [comment]
@mhines-usgs Awesome. Can you also stick lake areas in the `data-raw/area` directory?

**Comment by mhines-usgs** [comment]
@lawinslow sure, do you just want the ids and the area? or the same file?

**Comment by lawinslow** [comment]
Yes please!

**Comment by lawinslow** [comment]
Just the same file.

**Comment by lawinslow** [comment]
as in an areas file with "id, area" header, m^2 preferred if possible.

**Comment by mhines-usgs** [comment]
@lawinslow check it ^^ https://github.com/mhines-usgs/lakeattributes/commit/6e1dc3ece3c8b1f51894a24a82ac5d779fd6f032

**Comment by mhines-usgs** [comment]
Oops, wait, wrong field output.

**Comment by lawinslow** [comment]
Awesome. Thanks!

**Pull request merged**
